accMngrCount:
    path: /count
    controller: App\Controller\AccountManager\Main::count
    methods: [GET]
    
accMngrPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]
    
accMngrAccounts:
    path: /accounts
    controller: App\Controller\AccountManager\Main::accounts
    methods: [GET]

accMngrAccountForm:
    path: /account/form/{id}
    controller: App\Controller\AccountManager\Main::accountForm
    requirements:
        id: \d+
    defaults: 
        id: -1
    methods: [GET]

accMngrAccountPost:
    path: /account/post
    controller: App\Controller\AccountManager\Main::accountPost
    methods: [POST]

accMngrPasswordForm:
    path: /password/form/{id}
    controller: App\Controller\AccountManager\Main::passwordForm
    requirements:
        id: \d+
    defaults: 
        id: -1
    methods: [GET]

accMngrSetPassword:
    path: /password/set
    controller: App\Controller\AccountManager\Main::passwordSet
    methods: [POST]
