budgetPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]

budgetWidget:
    path: /widget
    controller: App\Controller\Budget\Main::widget
    methods: [GET]

budgetList:
    path: /list
    controller: App\Controller\Budget\Main::list
    methods: [GET]
    
budgetData:
    path: /data/{budget_id}
    controller: App\Controller\Budget\Main::data
    methods: [GET]
    defaults:
        budget_id: 0
    requirements:
        budget_id: \d+

budgetItemForm:
    path: /item/form/{id}
    controller: App\Controller\Budget\Item::form
    methods: [GET]
    defaults:
        id: 0
    requirements:
        id: \d+
        
budgetItemCreateForm:
    path: /item/form/create/{budget_id}/{parent_id}
    controller: App\Controller\Budget\Item::createF
    methods: [GET]
    defaults:
        parent_id: 0
        budget_id: 0
    requirements:
        parent_id: \d+|-1
        budget_id: \d+        
        
budgetItemCreate:
    path: /item/create
    controller: App\Controller\Budget\Item::create
    methods: [POST]

budgetItemPost:
    path: /item/post
    controller: App\Controller\Budget\Item::post
    methods: [POST]

budgetItemDelete:
    path: /item/delete/{id}
    controller: App\Controller\Budget\Item::delete
    methods: [GET]
    defaults:
        id: 0
    requirements:
        id: \d+

budgetItemNameAdd:
    path: /item/name/add/{name}
    controller: App\Controller\Budget\Item::nameAdd
    methods: [GET]
    defaults:
        name: ''
        
budgetItemChoices:
    path: /item/choices/{budget_id}
    controller: App\Controller\Budget\Item::choices
    methods: [GET]
    defaults:
        budget_id: 0
    requirements:
        budget_id: \d+
    
budgetDiscountsPage:
    path: /discounts/page
    controller: App\Controller\Application::index
    methods: [GET]
    
budgetDiscountsData:
    path: /discounts/data
    controller: App\Controller\Budget\Discount::data
    methods: [GET]
    
budgetDiscountForm:
    path: /discount/form/{land_id}/{item_name_id}
    controller: App\Controller\Budget\Discount::form
    methods: [GET]
    requirements:
        land_id: \d+|-1
        item_name_id: \d+|-1
    defaults: 
        land_id: -1
        item_name_id: -1
    
budgetDiscountPost:
    path: /discount/post
    controller: App\Controller\Budget\Discount::post
    methods: [POST]
    
budgetDiscountDelete:
    path: /discount/delete/{land_id}/{item_name_id}
    controller: App\Controller\Budget\Discount::delete
    methods: [GET]
    requirements:
        land_id: \d+|-1
        item_name_id: \d+|-1
    defaults: 
        land_id: -1
        item_name_id: -1
    
budgetSpendingCreateForm:
    path: /spending/create/form
    controller: App\Controller\Budget\Spending::createF
    methods: [GET]
    
budgetSpendingEditForm:
    path: /spending/edit/form
    controller: App\Controller\Budget\Spending::editForm
    methods: [GET]
    
budgetSpendingCreate:
    path: /spending/create
    controller: App\Controller\Budget\Spending::create
    methods: [POST]
    
budgetSpendingPost:
    path: /spending/post
    controller: App\Controller\Budget\Spending::post
    methods: [POST]
    
budgetSpendingDelete:
    path: /spending/delete/{id}
    controller: App\Controller\Budget\Spending::delete
    methods: [GET]
    requirements:
        id: \d+|-1
    defaults: 
        id: -1
  