budgetPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]

budgetWidget:
    path: /widget
    controller: App\Controller\Budget\Main::widget
    methods: [GET]

budgetList:
    path: /list
    controller: App\Controller\Budget\Main::list
    methods: [GET]
    
budgetData:
    path: /data/{budget_id}
    controller: App\Controller\Budget\Main::data
    methods: [GET]
    defaults:
        budget_id: 0
    requirements:
        budget_id: \d+

budgetItemForm:
    path: /item/form/{id}
    controller: App\Controller\Budget\Item::form
    methods: [GET]
    defaults:
        id: 0
    requirements:
        id: \d+
        
budgetItemCreateForm:
    path: /item/form/create/{budget_id}/{parent_id}
    controller: App\Controller\Budget\Item::createF
    methods: [GET]
    defaults:
        parent_id: 0
        budget_id: 0
    requirements:
        parent_id: \d+|-1
        budget_id: \d+        
        
budgetItemCreate:
    path: /item/create
    controller: App\Controller\Budget\Item::create
    methods: [POST]

budgetItemPost:
    path: /item/post
    controller: App\Controller\Budget\Item::post
    methods: [POST]

budgetItemDelete:
    path: /item/delete/{id}
    controller: App\Controller\Budget\Item::delete
    methods: [GET]
    defaults:
        id: 0
    requirements:
        id: \d+

budgetItemNameAdd:
    path: /item/name/add/{name}
    controller: App\Controller\Budget\Item::nameAdd
    methods: [GET]
    defaults:
        name: ''
    