electricityUploadForm:
    path: /form
    controller: App\Controller\Electricity\Upload::form
    methods: [GET]
    
electricityUpload:
    path: /upload
    controller: App\Controller\Electricity\Upload::upload
    methods: [POST]

electricityBills:
    path: /bills/{year}/{month}
    controller: App\Controller\Application::index
    methods: [GET]
    defaults:
        year: 0
        month: 0
    requirements:
        year: \d+
        month: \d+
        
electricityBillsForm:
    path: /bills/form/{year}/{month}
    controller: App\Controller\Electricity\Bills::form
    methods: [GET]
    defaults:
        year: 0
        month: 0
    requirements:
        year: \d+
        month: \d+

electricityBillsData:
    path: /bills/data
    controller: App\Controller\Electricity\Bills::data
    methods: [POST]

electricityBillAddForm:
    path: /bills/add/form
    controller: App\Controller\Electricity\Bills::addForm
    methods: [GET]

electricityBillAdd:
    path: /bills/add
    controller: App\Controller\Electricity\Bills::add
    methods: [POST]

electricityExcelInvoice:
    path: /bills/excel/invoice/{invoice_id}
    controller: App\Controller\Electricity\Bills::excelInvoice
    methods: [GET]
    defaults:
        invoice_id: 0
    requirements:
        invoice_id: \d+
