electricityUploadForm:
    path: /form
    controller: App\Controller\Electricity\Upload::form
    methods: [GET]
    
electricityUpload:
    path: /upload
    controller: App\Controller\Electricity\Upload::upload
    methods: [POST]
