extDataUploadForm:
    path: /upload/form
    controller: App\Controller\ExtData\Upload::form
    methods: [GET]

extDataUpload:
    path: /upload/post
    controller: App\Controller\ExtData\Upload::post
    methods: [POST]

extDataPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]
    
extDataData:
    path: /page/data
    controller: App\Controller\ExtData\Page::data
    methods: [GET]
    
extDataPost:
    path: /item/post
    controller: App\Controller\ExtData\Item::post
    methods: [POST]

extDataEditForm:
    path: /item/editform/{id}
    controller: App\Controller\ExtData\Item::form
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1    

extDataBudgetItemChoices:
    path: /item/budgetitem/choices/{budget_id}
    controller: App\Controller\ExtData\Item::budgetItemChoices
    methods: [GET]
    requirements:
        id: \d+|-1
    defaults: 
        id: -1
    