extDataUploadForm:
    path: /upload/form
    controller: App\Controller\ExtData\Upload::form
    methods: [GET]

extDataUpload:
    path: /upload/post
    controller: App\Controller\ExtData\Upload::post
    methods: [POST]

extDataPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]
    
extDataData:
    path: /data
    controller: App\Controller\ExtData\Main::data
    methods: [GET]
    
extDataPost:
    path: /post
    controller: App\Controller\ExtData\Main::post
    methods: [POST]
