extDataUploadForm:
    path: /upload/form
    controller: App\Controller\ExtData\Upload::form
    methods: [GET]

extDataUpload:
    path: /upload/post
    controller: App\Controller\ExtData\Upload::post
    methods: [POST]

extDataPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]
    
extDataData:
    path: /page/data
    controller: App\Controller\ExtData\Page::data
    methods: [GET]
    
extDataPost:
    path: /page/post
    controller: App\Controller\ExtData\Page::post
    methods: [POST]

extDataEditForm:
    path: /page/editform/{id}
    controller: App\Controller\ExtData\Page::form
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1    
