financeInvoice:
    path: /invoice/{id}
    controller: App\Controller\Finance\Invoice::data
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1

financeInvoicePage:
    path: /invoice/page/{id}
    controller: App\Controller\Application::index
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1

financeMoneyMovePage:
    path: /moneymove/page
    controller: App\Controller\Application::index
    methods: [GET]

financeMoneyMoveData:
    path: /moneymove/data
    controller: App\Controller\Finance\MoneyMove::data
    methods: [POST]
    
financeMoneyMoveFilterForm:
    path: /moneymove/filterform
    controller: App\Controller\Finance\MoneyMove::filterForm
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1    
    
financeMoneyMoveEditForm:
    path: /moneymove/editform/{table}/{id}
    controller: App\Controller\Finance\MoneyMove::editForm
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1
        table: ""

financeMoneyMoveCreateForm:
    path: /moneymove/createform
    controller: App\Controller\Finance\MoneyMove::createRecordForm
    methods: [GET]
    
financeMoneyMoveCreate:
    path: /moneymove/create
    controller: App\Controller\Finance\MoneyMove::create
    methods: [POST]
    
financeMoneyMovePost:
    path: /moneymove/post
    controller: App\Controller\Finance\MoneyMove::post
    methods: [POST]
    
financeMoneyMoveDelete:
    path: /moneymove/delete/{table}/{id}
    controller: App\Controller\Finance\MoneyMove::delete
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1    
        table: ""
        
financeSitePaysPage:
    path: /sitepays/page
    controller: App\Controller\Application::index
    methods: [GET]

financeSitePaysForm:
    path: /sitepays/form
    controller: App\Controller\Finance\SitePays::getForm
    methods: [GET]    

financeSitePaysData:
    path: /sitepays/data
    controller: App\Controller\Finance\SitePays::data
    methods: [POST]    