landPage:
    path: /page
    controller: App\Controller\Application::index
    methods: [GET]
    
landPageData:
    path: /page/data
    controller: App\Controller\Land\Main::pageData
    methods: [GET]
    
landPost:
    path: /post
    controller: App\Controller\Land\Main::post
    methods: [POST]

landDebtType:
    path: /debtbtype/{land_id}/{type_id}
    controller: App\Controller\Application::index
    methods: [GET]
    requirements:
        type_id: \d+
        land_id: \d+
    defaults: 
        type_id: -1
        land_id: -1

landDebtTypeData:
    path: /debtbbytype/data/{land_id}/{type_id}
    controller: App\Controller\Land\Main::debtType
    methods: [GET]
    requirements:
        type_id: \d+
        land_id: \d+
    defaults: 
        type_id: -1
        land_id: -1

landOwnersPage:
    path: /owners/page
    controller: App\Controller\Application::index
    methods: [GET]
    
landOwnersData:
    path: /owners/data
    controller: App\Controller\Land\Owner::data
    methods: [GET]
    
landOwnerForm:
    path: /owner/form/{id}
    controller: App\Controller\Land\Owner::form
    methods: [GET]
    requirements:
        id: \d+|-1
    defaults: 
        id: -1
    
landOwnerPost:
    path: /owner/post
    controller: App\Controller\Land\Owner::post
    methods: [POST]
    
landOwnerDelete:
    path: /owner/delete/{id}
    controller: App\Controller\Land\Owner::delete
    methods: [GET]
    requirements:
        id: \d+
    defaults: 
        id: -1

landDebtInvoiceChoices:
    path: /debt/invoice/choices/{land_id}/{charge_type_id}
    controller: App\Controller\Land\Main::debtInvoiceChoices
    methods: [GET]
    requirements:
        land_id: \d+
        charge_type_id: \d+
    defaults: 
        land_id: -1
        charge_type_id: -1
    