landDebtTypeData:
    path: /debtbbytype/data/{land_id}/{type_id}
    controller: App\Controller\Township\Land::debtType
    methods: [GET]
    requirements:
        type_id: \d+
        land_id: \d+
    defaults: 
        type_id: -1
        land_id: -1
