townshipDebt:
    path: /debt
    controller: App\Controller\Township\Main::debt
    methods: [GET]

townshipDebtByLines:
    path: /debt/{type}
    controller: App\Controller\Township\Main::debtByLines
    methods: [GET]
    requirements:
        type: \d+
    defaults: 
        type: -1

townshipContacts:
    path: /contacts
    controller: App\Controller\Application::index
    methods: [GET]
    